export const Endpoints = {
    AND: "&",
    API: "/api",
    COUNTRIES: "/countries",
    COUNTRY_NAME: "countryName",
    EQUALS: "=",
    FOOTBALL_API: "http://localhost:8080",
    IS_CLIENT_OFFLINE: "isClientOffline",
    LEAGUE_NAME: "leagueName",
    QUESTION_MARK: "?",
    TEAM_NAME: "teamName",
    VERSION_1: "/v1",
  };

export const Standings = {
  country_name: "",
  league_id: "",
  league_name: "",
  team_id: "",
  team_name: "",
  overall_promotion: "",
  overall_league_position: "",
  overall_league_payed: "",
  overall_league_W: "",
  overall_league_D: "",
  overall_league_L: "",
  overall_league_GF: "",
  overall_league_GA: "",
  overall_league_PTS: "",
  home_league_position: "",
  home_promotion: "",
  home_league_payed: "",
  home_league_W: "",
  home_league_D: "",
  home_league_L: "",
  home_league_GF: "",
  home_league_GA: "",
  home_league_PTS: "",
  away_league_position: "",
  away_promotion: "",
  away_league_payed: "",
  away_league_W: "",
  away_league_D: "",
  away_league_L: "",
  away_league_GF: "",
  away_league_GA: "",
  away_league_PTS: "",
  league_round: "",
  fk_stage_key: "",
  stage_name: "",
};
